name: epi-fm
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - numpy=1.22.0
  - pip:
    - tqdm
    - pandas==1.3.1
    - torchmetrics
    - pytorch==2.2.0
    - torchvision==0.17.0
    - torchaudio==2.2.0 
    - scanpy
    - pytorch-lightning==2.3.0
    - biopython
    - pyranges
    - transformers==4.43.2